#!/bin/bash

set -e
cd `dirname $0`
cd .. # .codapt
cd .. # project root

# check if the app is running
status_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/nonexistent)
if [[ $status_code =~ ^5[0-9][0-9]$ ]]; then
  echo "App is not running or experiencing server errors, exiting..."
  exit 1
fi

echo "App is running"
