#!/bin/bash

set -e
cd `dirname $0`
cd .. # .codapt
cd .. # project root

# stop all containers
scripts/docker-compose down --remove-orphans

# build
scripts/docker-compose build

# install dependencies, generate prisma client, push schema
scripts/docker-compose run --rm app bash -c "( NODE_ENV=development pnpm install ) && pnpm exec prisma db push --accept-data-loss && ( [ \"\$NODE_ENV\" = \"production\" ] && pnpm build || true ) && pnpm exec tsx src/server/scripts/setup.ts"
